### ISSUE TITLE
add/mul bad codegen for uint256+

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-stint#87]
Seen with @arnetheduck.

for uint128, stint properly generates add + adc (see https://github.com/status-im/nim-stint/issues/10)

But for uint256+, the way carry is done will loop multiple time on the low half
https://github.com/status-im/nim-stint/blob/9993b9dca4a2dbf76bc432252ad4e8db944ae831/stint/private/uint_addsub.nim#L17-L29

Important for WASM codesize optimization.

**Comment by arnetheduck** [comment]
the issue here is that we lack an `func addWithCarry(a, b: T): tuple[v: T, overflow: bool]` operation - both for normal integers and for this library - with such an operation one can write a recursive version of the algorithm that lines up the operations and carries in a single pass instead of the current inefficient comparison+add

**Comment by mratsim** [comment]
Implementation can follow recint which also uses recursive high/low limbs: https://github.com/linbox-team/givaro/blob/v4.1.1/src/kernel/recint/ruadd.h#L170

**Comment by mratsim** [comment]
Closed by array backend refactoring
